---
name: Checks
on: [push]
jobs:
  test:
    name: Test action
    runs-on: ubuntu-20.04 # github action runners
    steps: # 작성순서에 따라 실행
      - name: Login to Docker hub # 로그인을 해야 시간 당 이미지 최대 200개 pull 가능
        uses: docker/login-action@v1 # use pre-made action
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_DEV }}" > .env.dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
    # - name: Lint
    #   run: docker-compose run --rm app sh -c "flake8"
