---
name: Checks
on: [push]
jobs:
  test:
    name: Test action
    runs-on: ubuntu-20.04 # github action runners
    steps: # 작성순서에 따라 실행
      - name: Login to Docker hub # 로그인을 해야 시간 당 이미지 최대 200개 pull 가능
        uses: docker/login-action@v1 # use pre-made action
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Create env file
        run: |
          echo POSTGRES_DB=${{secrets.POSTGRES_DB}} > .env.dev
          echo POSTGRES_USER=${{secrets.POSTGRES_USER}} > .env.dev
          echo POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} > .env.dev
          echo DB_HOST=${{secrets.DB_HOST}} > .env.dev
          echo DB_NAME=${{secrets.DB_NAME}} > .env.dev
          echo DB_USER=${{secrets.DB_USER}} > .env.dev
          echo DB_PASSWORD=${{secrets.DB_PASSWORD}} > .env.dev
          echo DB_PORT=${{secrets.DB_PORT}} > .env.dev
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
    # - name: Lint
    #   run: docker-compose run --rm app sh -c "flake8"
